radiocosmology/draco

draco/analysis/sidereal.py
draco/core/containers.py

Added missing function _ensure_list to draco.analysis.sidereal.  Made sure that the __memh5_sublcass attribute is not populated incorrectly when attrs_from is passed to core.containers.ContainerBase.

Minor changes for merging draco with ch_pipeline/seth_dev_branch.

---

draco/analysis/sidereal.py
draco/core/io.py
draco/core/misc.py
draco/core/task.py
test/pipe_config.yaml

Initial support for MPI aware logging on pipeline tasks.
All `SingleTask` instances now have a `log` property returning a `logging.Logger` that can be used for logging messages. They also add information about the MPI process (rank and size) to the log record which can be displayed in the formatted message, and used for filtering.
There's also an `MPILogFilter` which can filter messages differentially based on the rank, in this case allowing us to accept messages with lower priorities on rank=0. By default rank=0 logs at the `logging.INFO` level and other ranks only at the `logging.WARN` level.
At the moment to enable the filtering and formatting aspects you need to call the `SetMPILogging` task, though in the long run I would like to expand the configurability of the logging in caput to …

MPI aware logging support

---

CHANGELOG.md
draco/__init__.py
draco/analysis/delay.py
draco/analysis/fgfilter.py
draco/analysis/flagging.py
draco/analysis/mapmaker.py
draco/analysis/powerspectrum.py
draco/analysis/svdfilter.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/core/task.py
draco/synthesis/stream.py
draco/util/tools.py
setup.py

This pull request introduces a major set of new functionality to draco:
- Adds in delay spectrum estimation and filtering.
- SVD based foreground filtering on the m-modes
- KL/SVD foreground filtering
- Quadratic power spectrum estimation
There's also a few minor changes:
- Added a new `LoadProductManager` task which loads the full interface to the driftscan generated analysis products. In many places this can be used instead of BeamTransfer or Telescope objects and so `LoadProductManager` should replace `LoadBeamTransfers` in most circumstances.
- Fixes to the logging support,

Power spectrum estimation and foreground filtering

---

draco/synthesis/stream.py

you have to give it stack 'None' so it won't crash in ExpandProducts

Expand Products fix with stack axis

---

draco/core/containers.py

For simulating timestream data, stack can only be created when prod is not None otherwise it crashes on line 687
`TypeError: object of type 'NoneType' has no len()`

stack can only be created when prod is not None

---

draco/analysis/transform.py
draco/core/containers.py
draco/util/_fast_tools.pyx
draco/util/tools.py

Significant speed ups to collate products:
- Moved calculate redundancy into a Cython function.
- Moved slicing of dataset to be outside tightloop to remove implied MPI
calls.

Fast collate products

---

draco/util/_fast_tools.pyx
draco/util/regrid.py

Significantly improves the speed of the regridder by restricting the
length of the inner summation when calculating the band matrix to only
the non-zero elements.

Improve regridding speed

---

draco/analysis/sidereal.py

If padding is chosen to be 0 (default) nothing changes in the code. If padding is set to some value then 'lsd_start' will correspond to the start of of the requested time frame including the padding.

Have SiderealGrouper support padding if requested

---

draco/core/io.py

Allows files to be loaded without any axes distributed.
Default value means it is backwards compatible with previous API.

feat(io): Add config option to LoadFilesFromParams

---

draco/analysis/delay.py

BREAKING CHANGE: DelayFilter now has a `setup` method and `requires` a telescope object.
Also fix normalization bug.

feat(delay): Add baseline dependent delay cut

---

draco/core/io.py

In the Python 3 automated porting the `next` method on the class got
changed to `__next__` and so wasn't being picked up.

fix(LoadMaps): fix issue in Python 3 porting that stopped maps loading

---

draco/core/containers.py

Add chunk/compression parameters to a couple of containers. By default, these will be ignored unless explicitly enabled with an option to the container initialiser.
This relies on https://github.com/radiocosmology/caput/pull/77.

Chunked hdf5

---

draco/analysis/transform.py

`CollateProducts` now creates the time axis of the output `TimeStream`
container from the `time` property of the input container, so that
the time axis is defined with respect to the integration centre
instead of the integration start.

fix(transform): use `time` property instead of `index_map['time']`

---

draco/analysis/transform.py

If the timestream that is input to CollateProducts is stacked, then
attempt to redefine its stack axis so that it only contains products
consisting of inputs that are not masked in the telescope instance.
Also moves determination of `bt_rev` from `process` to `setup` since
it only depends on the telescope instance.

fix(transform): try to redefine stack axis using only unmasked products

---

draco/analysis/transform.py

This fix broadcasts `mmodes` to correct shape before assignment to `marray` by rolling its last axis (the m-mode axis) to the first position. Without this fix get a `ValueError` when using `transform._pack_marray`

fix(transform._pack_marray): broadcast mmodes to correct shape before assignment to marray

---

draco/core/containers.py
draco/core/misc.py

In the pathfinder-era the weight dataset of StaticGainData
was being populated with the dynamic range of the eigenvalue
decomposition.  This is a single number per frequency.
Today we estimate the uncertainty on the gain as 1 / sigma^2
for each frequency AND input.

feat(containers): Add input axis to weight dataset of StaticGainData.

---

draco/core/task.py

This caused the pipeline to crash when the output container already had
the version or config tags present. This happens when `attrs_from` is
used to transfer over metadata.

fix(task): crash in key check when metadata already copied into the container

---

draco/analysis/delay.py

In version 1.18.0 randomgen changed the API from:
```from randomgen import RandomGenerator```
to
```from randomgen import Generator```

(fix): Update randomgen API

---

draco/analysis/sidereal.py
draco/analysis/transform.py

Fix a crash when the SiderealGrouper runs with no inputs and remove some useless print statements.

Fix crash print

---

draco/core/task.py
test/test_write_metadata.py

Instead of adding metadata as attributes to BasicCont, use the history
feature.
I didn't expect this to pass, but it did, because I moved all the tests that directly read h5 files into caput.
~Depends on~ Actually doesn't depend on https://github.com/radiocosmology/caput/pull/128 ...but looks nicer with it.
Fixes #88

fix(SingleTask): use memh5 history for metadata

---

draco/analysis/beamform.py
draco/analysis/flagging.py

The coordinates of the sources used in beamforming must be converted to
CIRS positions before beamforming or they'll be offset by the precessing
of the polar axis since J2000.
Fixes #87

fix(beamform): convert sources to CIRS coordinates before beamforming

---

draco/core/task.py

After https://github.com/radiocosmology/caput/pull/129, this was found to just break logging by overriding the root log level.

fix(SetMPILogging): don't override root log level

---

draco/core/containers.py
test/test_selections.py

This fixes the issues which was with the incorrect `._axes` attribute being checked because the correct `.axes` method can't be called from a class method. This sorts all of that out.

Fix selections with inherited axes

---

draco/core/containers.py

This commit passes along the distributed and comm properties of
the container when instantiating its copy.  It also prevents
distributed datasets in a non-distributed container.

fix(containers): fix copy for non-distributed data

---

draco/analysis/flagging.py

Previously the code distributed the array over m and then masked
the local m axis instead of globally.
This was causing the periodic artifacts at the declination of bright point sources.

fix(analysis.flagging.MaskData): Fix m mask.

---

draco/analysis/delay.py
draco/analysis/flagging.py

These build ontop of the work that's in #109, so once that's merged we'll need to rebase this PR.
The biggest thing in here is to introduce a new task which requires a stack and then for each input stream it takes a weighted average with a small amount of the stack to fill in holes. This reduces the artifacts in the estimated delay spectrum quite by around an order of magnitude on the data I've used for testing.

Delay filter/estimator fixes and BlendStack task

---

draco/analysis/beamform.py

- The normalization of the beamformed visibility was missing
a factor of the primary beam when collapsing over hour angle.
- Simplify the calculation of the uncertainty on the
beamformed visibility when using the inverse variance
weighting scheme.

fix(beamform): incorrect normalization for collapse_ha

---

draco/analysis/ringmapmaker.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/task.py
draco/util/tools.py

This is now ready for review. There's a few broader fixes in here, but the biggest change is the introduction of the componentised ring map maker.
I have tested this against the current ring map maker and it gives nearly identical maps, that differ at the 10^-3 level. Here is a comparison of the maps using uniform weighting:
The top panel is the map from the new map maker (from -10 Jy to 10 Jy), the middle panel is the difference between the old and new maps with the colour scale multiplied by 1000x (i.e. it's from +/- 10 mJy). The third is the difference if I apply a ~10^-3 level scale to the new map to get them to match better.
This is the same comparison but for natural weighting
One obvious question is: why is there any difference at all? Essentially it all comes down to how the …

Hybrid map maker

---

.github/workflows/main.yml
draco/core/io.py
draco/core/task.py

see https://github.com/radiocosmology/caput/pull/156
I don't think these should ever have been config errors, but please correct me if I'm wrong.

Deprecate caput.pipeline.PipelineConfigError

---

draco/core/task.py

I'm not sure if this will speed up `_nan_check_walk`, but I don't see how this line can have an effect anyways.
Percentages are of the total run time of the daily processing pipeline:
- 10% _nan_check_walk (draco.core.task)
- 7% __getitem__ (memh5)

perf(SingleTask): remove no-effect-__getitem__ call

---

draco/analysis/beamform.py

- Add capability to track sources for a declination
dependent amount of time, so that all sources are
tracked through the same angle on the sky.
- Add option to ignore primary beam model when beamforming,
i.e., use uniform weighting.
- Use the beam method of the telescope object to evaluate
the primary beam model.  Requires [PR 78](https://github.com/chime-experiment/ch_pipeline/pull/78)
of ch_pipeline for the CHIME implementation.
- Move the parameterized fit to the driftscan beam out of
this module and into its own telescope class in ch_pipeline.
- Check if a catalog is already in CIRS coordinates.
- Add the catalog's tag to the output container's tag.
- Create versions of the beamforming tasks that use an
external beam model provided at setup in a GridBeam container.

feat(beamform): refactor how primary beam model is evaluated

---

draco/analysis/delay.py

Add a dataset config property to the DelayFilterBase and
DelaySpectrumBase tasks to enable delay filtering and
spectrum estimation of containers that do not have a
vis dataset.

feat(delay): compatibility with RingMap and GridBeam containers

---

.github/workflows/main.yml
draco/analysis/beam.py
draco/analysis/ringmapmaker.py
draco/analysis/transform.py
draco/core/containers.py

This fixes a nasty bug where MPI calls could get out of sync when using
`DeconvolveAnalyticalBeam` in a case where different ranks have
differing numbers of frequencies. To rectify this it refactors the code
such that the beam_mmodes are generate for all frequencies at once which
will prevent the bug from resurfacing in newer implementations.

fix(ringmapmaker): MPI calls could get out of sync

---

draco/analysis/sourcestack.py

This collects a few minor changes to `draco.analysis.sourcestack.SourceStack`:
- Allowing the use of input `FormedBeam` containers where the frequency axis is either increasing or decreasing. The convention for this is opposite in the `CHIME` telescope class and a generic `driftscan` telescope, so this change allows for stacking with non-`CHIME` telescopes.
- An option to only stack on sources within a specific frequency bin (useful for isolating the stacking signal within a narrow frequency range, as opposed to averaging across the entire band).
- Changing variables and comments to refer to sources instead of quasars/QSOs.

Misc. tweaks to SourceStack

---

pyproject.toml

Binaries compiled with old Numpy versions are ABI compatible with
newer Numpy versions, but not vice-versa.
Discussion on this here: https://numpy.org/devdocs/user/depending_on_numpy.html
To avoid running issues into on cedar, we should build using the oldest
compatible numpy version. We can then run packages using whatever newer
Numpy version we want.
Conversation here: https://github.com/radiocosmology/draco/pull/145
This does fail the following test:
```
deactivate                                                                                                                                                                                      
mkdir -p ./venv …
```

build: build using the oldest supported version of numpy, for python version

---

draco/synthesis/mockcatalog.py

This refactors Seth's eBOSS redshift error code into a separate task, and implements a few other minor tweaks.

Task to add eBOSS-like redshift errors to catalog

---

draco/core/task.py

- fixes bug where pipeline exceptions, if a task returns a None as a
result to `.finish`
```
59
5360.3s [MPI  89/128] - INFO     draco.analysis.sidereal.SiderealGrouper: self._timestream_list: [<draco.core.containers.TimeStream object at 0x2b3ac5d29220>, <draco.core.containers.TimeStream object at 0x2b3ac5cc61f0>]                                                                                                                                                                
5360.3s [MPI   0/128] - INFO     draco.analysis.transform.CollateProducts: Profiling pipeline: 6 cores available. …
```

fix(task): if finish task output is None, it should not be processed

---

draco/core/containers.py

For some reason ContainerBase doesn't call its superconstructor via `super()`
but with a direct class reference. Unfortunately in sitations with multiple
inheritance this results in objects not being correctly initialised as the
explicit class reference wasn't actually next in the MRO.
I'm not sure if this is clearly a bug, or if it's actually a deliberate choice
that I don't understand the rationale behind. At the moment I don't see how it
can make any difference, there are very few containers using multiple
inheritance and they don't typically have constructors, so I can't really
envisage a scenario where `super()` would call something different from the
explicit call.
Anyway, this should at least be tested by running through a day of the daily
pipeline with it.

fix(ContainerBase): correctly call superconstructor

---

draco/analysis/delay.py
draco/core/task.py

Fixes bug introduced in bbbc6b4505e7065ca1c50f0784e11a8c7775dbe6. Input
tags stopped being referenced when setting the tag on the output.
Needed to tag delayspectrum files properly in the daily pipeline.
This reverts to previous behaviour. If this was behaviour that was intentionally removed, we will need to ensure that the tag is properly set on `delayspectrum` output containers.

fix(SingleTask): pull tag from input_tags, when not explicitly configured

---

draco/core/task.py

If an input to `process` doesn't have a tag, `None` is added to this list. When the container is written to disk, the attributes parser in `memh5.copyattrs` doesn't catch a list of mixed types (`str` and `None` in this case) and output to HDF5 fails.
Maybe we'd like `memh5` to parse these mixed lists as well (possibly by checking for `dtype("O")`) but I think it also makes sense that the input tags be strings (this PR).

fix(task.SingleTask): ensure input tags are strings.

---

draco/util/_fast_tools.pyx
draco/util/tools.py
test/test_tools.py

Refactor `invert_no_zero` to avoid unnecessary memory copies

---

.github/workflows/main.yml
doc/requirements.txt
draco/analysis/beam.py
draco/analysis/dayenu.py
draco/analysis/ringmapmaker.py
draco/core/containers.py
draco/core/io.py
draco/core/task.py
draco/synthesis/mockcatalog.py
draco/synthesis/noise.py
requirements.txt
test/test_containers.py
test/test_io.py
test/test_selections.py

Depends on changes in https://github.com/radiocosmology/caput/pull/169

feat(task): zarr support

---

draco/util/tools.py
test/test_tools.py

I think the fix turns out to be trivial in here, as all the new MPIArray code means that `.empty_like` does exactly what you would want it to.

fix(invert_no_zero): issue when operating on MPIArrays

---

draco/core/containers.py

It looks like the copy was accidentally swapped with the original container when setting the compression parameters.

fix(containers): fixes bug setting compression parameters for copy

---

draco/analysis/flagging.py

Trying to apply the mask to the .local_array results in an
AttribteError. This should fix the issue, although an mpiarray warning
will occur. This reverts a change made in #185

fix(ApplyRFIMask): don't apply mask to local array.

---

draco/analysis/transform.py
draco/core/containers.py

The call to redistribute is only needed if the frequency axis has to be reordered. In many cases this doesn't have to happen, so we can do the task while distributed across frequency, avoiding an expensive `redistribute` call. This checks to see if the frequency mapping is sorted, and if it is it does not redistribute. Without redistributing, the task takes 70-80s total in the daily pipeline, down from around 2500s when redistributing every time.

Speed up `CollateProducts` by avoiding `redistribute` when possible.

---

draco/synthesis/mockcatalog.py

Updated z_weights_sum calculation in mockcatalog.py to use new MPIArray allreduce method instead of
the allreduce function which was failing.

updated z_weights_sum calculation

---

draco/util/_fast_tools.pyx
draco/util/tools.py

Accompanies radiocosmology/caput#221

Move _invert_no_zero to caput and add deprecation warning

---

draco/analysis/delay.py
draco/analysis/svdfilter.py
draco/analysis/transform.py

This PR has turned into a Frankenstein of various edits, but they are all relatively minor:
- Fix a few MPIArray warnings I've found in various tasks.
- Fix the following bug in `DelaySpectrumEstimatorBase`: if the input container has a large number of "baselines" with zero data or weights, such that there is an MPI rank that only contains these baselines, the routine that initializes the random number generator will never be called on this rank, because `self.rng` is only called in the argument of `delay_spectrum_gibbs()` in the main loop: https://github.com/radiocosmology/draco/blob/16035533fda1d3af6393f8550ea4424af6808c49/draco/analysis/delay.py#L671-L716, and this will always be skipped. The solution is to explicitly initialize the RNG on all ranks before entering the loop, by calling …

Fix Gibbs sampler bug and add initial_amplitude parameter, and fix misc. MPIArray warnings

---

draco/core/misc.py

I noticed this issue in the logs of rev_06 3237, if one rank fails it will log the failure after the timeout, but other ranks might have already logged that they were successful, which is confusing. This should fix that by only logging success after all ranks have completed.

fix(misc): Log MPI check as successful only after all ranks complete

---

draco/util/_fast_tools.pyx

An internal loop indexed 1 past the end index, causing an out of bounds access at the end of an array, which resulted in NaNs being returned for some datasets. 
Closes #215

fix(band_covariance): fix out of bounds index in _band_wiener_covariance

---

draco/analysis/flagging.py

Gains are set to 1 when calibration determines some frequencies are bad. The gain interpolation region will also produce junk data, so this is designed to mask that. 
This PR has 3 commits:
1. A couple of documentation and naming updates (maybe shouldn't be in this PR)
2. A task to mask any weight above or below flat thresholds, mostly for avoiding numerical issues
3. A task to mask the gain boundary regions
This task is run for each individual timestream file then masks are combined and applied. It also requires subsequently using `ExpandMask` from `ch_pipeline` to actually mask the gain interpolation region AFTER individual timestreams have been grouped into a full day.

Mask gain interpolation region after bad calibration

---

draco/analysis/transform.py

Adds an option to `ShiftRA` to periodically wrap shifted RA coordinates, and the RA axis of any relevant dataset

feat(ShiftRA): add option to make shift 360-degree-periodic

---

draco/core/task.py

Using `.all()` is faster than `.sum()`, so we should only take the sum if we actually found a NaN/inf

perf(task): only count nans/infs if any are found

---

draco/analysis/flagging.py

Since this is just supposed to catch numerical issues, I'm moving the default thresholds much closer to the max/min float32 values.
I'm also interested in feedback about making this baseline-independent and just spitting out  a mask, since it's adding some baseline-dependent flagging at the moment.

fix(flagging): increase default threshold for static weight masking

---

draco/core/containers.py
test/test_containers.py

`index_map` dataset attributes will be copied when `axes_from` is set. The `.time` property is removed from `containers.TODContainer` as it will be moved to `caput.tod.TOData`.
Related PRs:
- https://github.com/radiocosmology/caput/pull/234
- https://github.com/chime-experiment/ch_pipeline/pull/168
- https://github.com/chime-experiment/ch_util/pull/52
Note: this PR will not pass CI checks until the `caput` PR is merged
Another note: This raises a deprecation warning from `numpy.array_equal`. This is an internal numpy issue and should be fixed in numpy 1.24 (we're running 1.22.2 on cedar)

Timestamp Alignment(2/4): Copy index_map dataset attributes and remove `time` property

---

draco/analysis/sensitivity.py
draco/analysis/transform.py
draco/synthesis/gain.py

Instead, the copy_from parameter will handle directly copying all index_map entries, including the time axis.

Timestamp fixes (1/1): Remove some unnecessary time axis copies

---

draco/analysis/sidereal.py

This PR ensures that the timestream list is cleared whenever a concatenated product is made. If concatenation is done in `process_finish`, rather than the clause in `.process` (L101), all of the timestream files will be kept around until the next time the pipeline iterates through all tasks. In the case of the daily pipeline, this often doesn't happen until partway through the second stage, causing it to use significantly more memory than needed.

perf(sidereal): clear timestream list after concatenation

---

draco/analysis/beamform.py

These lists can hold fairly large chunks of data which will not get cleared from memory until one pipeline iteration after `.finish` is called, which often happens out of order

feat(beamform): delete some class list attributes in 'process_finish'.

---

.gitignore
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
test/test_containers.py

Apply a reduction op across up to n-1 axes of a rank-n dataset. The reduction can be applied to more than one dataset in the container, and axis downselection can be applied to n-1 axes as well. A weight mask can optionally be generated, which masks values where the weights are zero and is broadcast to the dataset shape if possible. This mask can also be applied before doing the reduction, using a masked array.
The task tries to optimize redistribution by first trying to minimize the number of redistributions that happen and then trying to choose the best possible axes to redistribute over if needed. This is just being done by an inverse sort by axis length.
I've tested this a fair bit, but I wouldn't be surprised if there are still some edge cases that could break. It generally works as …

feat(transform): task to apply reduction ops to a container

---

draco/analysis/delay.py
draco/core/containers.py

This is meant to supersede #176 and #216:
- Refactors `DelaySpectrumEstimator`, `DelaySpectrumEstimatorBase`, and `DelaySpectrumWienerBase` to eliminate repeated code blocks and enable future extensions
- Implements the fixes and features from #216 
Notably, I've kept the scheme of compressing many axes into a `baseline` axis. I don't think this is ideal in the long run, but in the short term, I think it's higher-priority to get the Wiener filter and #216 features all merged coherently

Refactor delay-space measurement code and add features

---

draco/analysis/ringmapmaker.py
draco/core/containers.py
draco/core/io.py

Previous version gives the correct result for CHIME, but can result in incorrect values for the grid spacing and indices for other telescopes due to a bug in how the shortest baseline is identified.

fix(ringmapmaker): fix bug finding shortest baseline in find_basis

---

draco/analysis/beam.py
draco/analysis/beamform.py
draco/analysis/dayenu.py
draco/analysis/delay.py
draco/analysis/fgfilter.py
draco/analysis/flagging.py
draco/analysis/mapmaker.py
draco/analysis/powerspectrum.py
draco/analysis/ringmapmaker.py
draco/analysis/sensitivity.py
draco/analysis/sidereal.py
draco/analysis/sourcestack.py
draco/analysis/svdfilter.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/core/misc.py
draco/core/task.py
draco/synthesis/gain.py
draco/synthesis/mockcatalog.py
draco/synthesis/noise.py
draco/synthesis/stream.py
draco/util/random.py
draco/util/regrid.py
draco/util/testing.py
draco/util/tools.py
pyproject.toml

These additions are useful for improving overall quality and consistency of code and eliminating extra things for PR reviewers to check. The ruff python version is set to python 3.8, since this is the minimum supported version. 
- isort: formats and alphabetically orders imports
- pyupgrade: upgrade syntax for newer versions of python (based on the version specified in pyproject.toml)
- numpy: check deprecated types
- ruff-specific: ambiguous unicode, collection instead of concatenation
- flake8-blind-except: don't allow blind `except` statements
- flake8-comprehensions: use comprehensions instead of concatenation where possible
- flake8-return: consistent and clear return statements
Additional ignored rules:
- NPY002: replace legacy numpy.random calls with np.random.Generator
I'm happy …

ci(ruff): add extra linting rules: isort, pyupgrade, numpy, ruff-specific

---

draco/analysis/flagging.py

I'm not sure why this didn't pop up sooner, but at the moment this task will leave the sidereal stream in a non-ideal state, with the `weights` dataset distributed differently from the rest of the container. This just makes sure that both the mask and the sidereal stream are reverted to a standard distribution

Redistribute back to frequency after generating baseline mask

---

draco/core/io.py

Allow glob patterns that do not contain the `*` wildcard but do contain `?` or character ranges delimited by `[]`.

feat(core.io): support globs without `*`

---

draco/analysis/delay.py
draco/analysis/ringmapmaker.py
draco/analysis/transform.py
draco/analysis/wavelet.py
draco/core/containers.py
draco/util/_fast_tools.pyx
requirements.txt

- refactor(DelaySpectrumEstimatorBase): remove unnecessary setup method
- refactor(delay): routine to flatten selected axes of a distributed dataset
- feat(wavelet): wavelet power spectrum estimation

Wavelet Power Spectra

---

draco/analysis/transform.py
draco/core/containers.py

- feat(containers): add DataWeightContainer to abstract over generic inputs
- feat(containers): add VisBase as a very generic container for visibilities
- feat(HPFTimeStream): high pass filter a generic timestream

Timestream high pass filter

---

draco/analysis/delay.py
draco/core/containers.py
draco/core/misc.py
draco/util/random.py
draco/util/testing.py

This contains all the parts of the cross delay PS branch that will cleanly merge.

Delay cross 1

---

draco/analysis/delay.py

Optionally provide a file path with a delay power spectrum to use as the initial estimate for the Gibbs sampler. Works with both the standard and cross power spectrum estimators. 
~~This is based on #255 and should be rebased once that is merged (or just merged into that PR)~~ Done

Optionally load an initial delay spectrum sample 

---

draco/core/containers.py
draco/synthesis/noise.py

Commit https://github.com/radiocosmology/draco/commit/32da5d4553d1fb32d3268a050b231db3e8cb88c3 broke the call to `util.random.complex_normal` in `synthesis.noise.GaussianNoise`, and this fixes it. (Bug discovered by @PanChristeas)

fix(GaussianNoise): fix bug in noise generation

---

draco/analysis/dayenu.py
draco/analysis/powerspectrum.py
draco/analysis/sidereal.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/core/misc.py
draco/core/task.py
draco/util/random.py
draco/util/tools.py
pyproject.toml

See [PEP 526](https://peps.python.org/pep-0526/). Mutable class attributes should be annotated with `typing.ClassVar`. I think that this makes sense in the cases I've implemented it, but I'm open to arguments.
Also, remove Sphinx < 5 version pin and set sphinx language to English

Enforce linting rule RUF012 

---

draco/analysis/delay.py
draco/analysis/flagging.py
draco/util/tools.py
requirements.txt

Adds a new RFI mask and a couple of extra tools
2-stage RFI mask
- high-pass m filter to isolate transient rfi
- low-pass m filter and sum threshold over frequencies to isolate narrowband rfi
- Update `null_delay_filter` to optionally low or high pass
- Add a task to taper a 2D mask
- Add a task to calculate a baseline estimate for a 1D spectrum in the presence of outliers. Works quite well - ~too computationally expensive to extend to 2D so I didn't end up using it in the RFI filter~ This might not actually be true - going to investigate

Add a new RFI Flagging task

---

draco/analysis/sensitivity.py

Fixed bug in ComputeSystemSensitivity when exclude_intracyl was set to true.  The inter-cylinder baselines were not being identified correctly when calculating the `measured` sensitivity dataset due to the CHIME cylinder rotation.  This resulted in 30 MHz ripples as a function of frequency when calculating the normalized sensitivity (`measured / radiometer`) from which the RFI mask is derived.  These ripples would change slightly with each gain updates, causing discontinuities in the metric that we were flagging on.

fix(sensitivity): fix bug in exclude_intracyl sensitivity calculation

---

draco/analysis/dayenu.py
draco/analysis/flagging.py
draco/analysis/transform.py

Adds three new tasks:
- analysis.dayenu.DayenuDelayFilterFixedCutoff enables delay filtering of timeseries with rapidly changing frequency masks.
- analysis.transform.ReduceChisq calculates a chi2-per-dof test statistic by comparing the delay filtered visibilities to the inverse noise variance stored in the weights.
- analysis.flagging.RFIMaskChisqHighDelay generates a mask from this chi2-per-dof test statistic.

feat(flagging): mask rfi based on delay filtered visibilities

---

draco/analysis/flagging.py
draco/analysis/sidereal.py
draco/core/containers.py
draco/util/regrid.py

Implements a rebinning task similar to #266. This updated version uses the actual per-baseline weights, rather than a mean, and avoids creating a separate `rebin_weight` dataset entirely. This should provide marginally better rebinning behaviour in the presence of bad baselines, and does not require complicated tracking of multiple datasets throughout various pipelines.
It also implements a baseline-dependent `effective_ra` dataset and a simplified `effective_ra` centring correction.
From testing, this seems to show a light reduction in noise across all delays compared to the mean-weighted rebinning.
- The rebinning has been tested through the chime daily pipeline
- Gradient correction has been tested
- Stacking of daily data has not been tested, but is assumed to be ok given no issues …

Baseline-dependent rebinner

---

draco/util/rfi.py

Also removes unnecessary slices.

fix(rfi): fix misalignment between mask and data in sumthreshold

---

draco/analysis/flagging.py
draco/core/task.py
draco/util/rfi.py

Three updates:
1. Add functionality for tasks to save multiple outputs
- The ability for a task to pass along more than one output was added in radiocosmology/caput#258. This update also allows tasks to *save* multiple outputs
2. Remove the second MAD over bright transits and daytime data from the Stokes I RFI mask. This was not behaving well near the edges of heavily flagged regions, and sensitivity-based flagging should be able to catch any RFI that gets through. Also, save out the mean power metric which is used in the sum threshold flagging step so that we can look at it.
3. Update the implementation of `sumthreshold`. This update is mostly to simplify the code, but it also offers a 10-25% speed improvement. NOTE: `ndimage.convolve1d` takes the negative of `origin` and calls …

Save out multiple files per task and tweak Stokes I RFI task

---

draco/analysis/flagging.py
draco/util/rfi.py

Some miscellaneous bug fixes:
- Use `np.ndarray` instead of `mpiarray.MPIArray` in `MaskBaselines`. This was causing an error in python 3.11+ because ufunc `where` is not defined for distributed arrays
- Change the minimization method used by `minimize_scalar` in `MaskFreq`. The previous method `golden` would fail with newer versions of scipy because it could not find a valid [bracket](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bracket.html#scipy.optimize.bracket). I _believe_ that this is because the function being minimized is roughly monotonically decreasing, so the criteria `func(xb) < func(xa) and func(xb) < func(xc)` could not be met. (See: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize_scalar.html). I also tried using a …

Assorted bug fixes

---

draco/analysis/delay.py
draco/analysis/delayopt.py
draco/analysis/flagging.py
draco/core/containers.py
requirements.txt

- feat(delay): maximum likelihood power spectrum estimator
- feat(delay): add option to use maximum likelihood estimator in tasks

Maximum likelihood delay power spectrum estimator

---

draco/analysis/dayenu.py

Redistributing over `el` fails on the `rms` dataset. I tried removing it, but now I'm getting a segfault when it tries to write out the ringmap to disk. So I think there may still be references to the `rms` dataset somewhere.
Any help figuring this out appreciated.

fix(analysis.DayenuDelayFilterMap): Remove rms dset

---

draco/analysis/sidereal.py
draco/analysis/transform.py
draco/util/regrid.py

Multiple fixes for tracking effective ra and applying a gradient correction:
- Initialize the `effective_ra` dataset in the stack container
- Properly replace the effective ra of masked samples with the bin centre ra
- Handle NaN values in the visibility gradient where the ra step is 0

Fix visibility gradient correction for quarterstacks

---

draco/core/containers.py

This method has been implemented in 'MemDiskGroup' in 'caput.memh5', so there is no need to overwrite it here now.
Relies on radiocosmology/caput#239 to properly implement shared datasets.

feat(containers): remove '.copy' method from ContainerBase.

---

draco/synthesis/noise.py

Resolves an error thrown in `GaussianNoiseDataset` when an MPIArray is passed to `random.complex_normal()`.

fix(GaussianNoiseDataset): explicitly operate on local_array

---

draco/util/random.py

numpy random Generator methods do not check the datatype of an output array, so if the output dtype is not the default (np.float64), the dtype must be explicitly passed to the generator.
Closes #288

Pass dtype argument to numpy random Generator

---

draco/analysis/ringmapmaker.py

Otherwise, the dataset will remain empty which can introduce NaN values and takes up memory when saved.
This appears to be the source of NaN values in some of the beamformed datasets in the daily filtered pipeline

Only initialize dirty_beam dataset if it will be used

---

draco/analysis/transform.py
draco/core/io.py

Adds the ability for `SelectionsMixin` to make selections based on index_map entries. This has to be explicitly enabled with the `allow_index_map` attribute, and will raise an error if an item is not found in the index map.

Allow selection from index map values

---

draco/analysis/sidereal.py

For example, if a `ch_pipeline.core.containers.CHIMETimeStream` object was passed to `SiderealRebinner`, the task would fail

Include subclasses in sidereal container map

---

draco/analysis/delay.py

We originally set these defaults to try to mimic the behaviour of the old Delay Power Spectrum code. However, that behaviour can't be reproduced exactly, since it would end up multiplying a mask into the data (no matter how complex), and instead we ended up introducing default behaviour which would not mask in RA.

Change DPS time_frac and remove_mean defaults to have more expected behaviour

---

draco/analysis/dayenu.py

`self.sstream` is set in the `setup`, but `self.stream` doesn't exist

Typo when checking properties of stored sstream

---

draco/analysis/transform.py

MixData contains much of the functionality needed to perform a jackknife of two datasets.  This adds two config flags that (1) will invert the weights prior to mixing and so that uncertainty is propagated correctly and (2) flags any samples where the weight is zero in any of the input data.  It also creates a new Jackknife task that has the config properties set to the correct values for performing a jackknife of two datasets.

feat(transform): update MixData to enable jackknifes

---

draco/analysis/sensitivity.py
draco/analysis/transform.py
draco/core/io.py

Pulls some useful functionality from #259.
These commits are required when to broadcast weights when compressing a `HybridVisStream`, but were previously contained in a much larger PR

Truncation weight broadcasting and get weights from a property

---

draco/core/io.py

Useful for loading auxiliary files when iterating over the primary data products.  For example, as one iterates over LSDs during quarter stacking, this can be used to load the appropriate rfi mask for each sidereal day.

feat(io): class for loading files from attributes of an input container

---

draco/core/task.py

When I implemented handling for multiple outputs, for some reason I didn't include the option to save only certain outputs to disk.
There are no unit tests for this since we don't have unit tests for tasks. I want to start doing that at some point, at least to test basic task infrastructure.

Optionally save only some output files

---

draco/analysis/flagging.py
draco/core/containers.py

The current RFI flagging allows only frequency and time/RA masks. I added two containers, **LocalizedRFIMask(freq, el, time)** and **LocalizedSiderealRFIMask(freq, el, ra)**, in core/containers.py, as well as three tasks, **SiderealMaskConversion**, **ReduceMaskEl**, and **ApplyLocalizedRFIMask**, in analysis/flagging.py, to enable elevation-specific directional RFI flagging in addition to freq and time/RA.

Tasks and containers for directional RFI mask

---

draco/analysis/ringmapmaker.py
draco/core/containers.py

Calculating the redundancy is computationally expensive and is only required if using a natural weighting scheme in `BeamformNS`.  This PR adds a config property `save_redundancy` to `MakeVisGrid` that when set to False will skip the calculation.
The PR also speeds up MakeVisGrid significantly by accessing local arrays outside of the for loop, preventing repeated MPIArray calls.  It fixes a longstanding bug in how redundancy was assigned that affected intracylinder baselines.  It also resolves some warnings related to MPIArray operations in RADependentWeights.

feat(ringmapmaker): ability to skip calculating the redundancy

---

draco/analysis/delay.py
draco/analysis/interpolate.py
draco/analysis/transform.py
draco/util/dpss.py
pyproject.toml

I want to look more into doing simultaneous frequency-ra interpolation, but this code is mostly complete and tested, so I think it's ready to be a PR.
This PR implements DPSS-based inpainting over a single axis, following the implementation in HERA's paper (https://arxiv.org/abs/2411.10529). It's been tested to work as-expected over both frequency and RA, with the caveat that it does not convert the RA axis to radians, which needs to be taken into account when selecting an appropriate cutoff. 
Implements all the actual inpainting code. Only the diagonal of the final covariance is returned. 
Implements inpainting as a task. Includes a base task, which applies a constant cutoff over a single axis, and tasks which try to calculate a per-baseline foreground cutoff for frequency and ra. …

DPSS inpainting and FFT delay transform

---

draco/analysis/ringmapmaker.py
draco/analysis/transform.py

Generates visibility weights that will match hybrid beamformed
visibility weights after beamforming north-south.  Useful for
generating noise realizations of hybrid beamformed visibilities
that maintain proper correlation along the el axis.

feat(ringmapmaker): create ReconstructVisWeight task

---

.github/workflows/main.yml
.github/workflows/sphinx.yml
draco/analysis/delay.py
draco/analysis/flagging.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/core/misc.py
draco/core/task.py
draco/util/random.py
draco/util/regrid.py
draco/util/testing.py
pyproject.toml

The minimum pinned version is based on fixes related to numpy 2 vs numpy 1 behaviour. Since we want to support numpy 2, we should use this minimum version. 
Also, there's an `astropy` import somewhere in `draco`, but it isn't included in the dependencies.

Bump Python 3.10-3.13 and include astropy dependency

---

draco/analysis/ringmapmaker.py
draco/analysis/transform.py

There are a few critical improvements here:
- Use the `out` kwarg where possible to avoid unnecessary duplicate arrays
- Use a faster method to find masked baselines
- Use `.local_array` to avoid `mpiarray` read/writes
- Remove `for` loops during mmode transform and write
- Use fast `fftw` module for m transform
- Apply m-mode normalization when writing to the `mmode` array - this was surprisingly almost ⅓ of the function runtime

Speed up mmode and BeamformNS

---

draco/synthesis/stream.py

Adds tasks to interpolate a sidereal dataset onto a time axis provided by another container.
1. Main tasks iterates sidereal stream and time axis
2. Second task iterates time axis for a fixed sidereal stream
3. Third task iterates sidereal stream for a fixed time axis
Also, refactors the existing task.
Interpolation is just done using the lanczos kernel, with no attempt made to compute weights (under the assumption that we don't care). If weights are needed, we can figure out how to do that.
Seems to work.

Update timestream synthesis tasks to take time input from another dataset

---

.gitignore
draco/analysis/delay.py

Yukari noticed this was crashing.
Numpy-2.0 removed the `ptp` method from `ndarray`.

fix(null_delay_filter): Fix ptp() call

---

draco/analysis/delay.py
draco/analysis/delayopt.py
draco/core/containers.py
draco/util/kernels.py

This PR refactors certain parts of the delay transform/power spectrum code, and provides performance improvements to the NRML, Gibbs, and Wiener filter estimators. It's based against #318, so that needs to be reviewed/merged first.
This PR adds two functional changes to the NRML estimator:
1. Switches to using a matern prior rather than a gaussian. Using the [matern kernel](https://en.wikipedia.org/wiki/Matérn_covariance_function) results in faster convergence and reduces excessive smoothing introduced by the gaussian prior. It also ends up being a bit less sensitive to specific hyperparameters, and is better able to model large (multiple orders of magnitude) jumps in power.
2. Imposes numerical bounds on the minimization parameters to eliminate overflows in the exponential. This isn't …

Delay transform refactor and performance improvements

---

draco/analysis/flagging.py
draco/analysis/transform.py

In #318, the `stokes_I` function was changed to maintain the standard visibility axis order. This task, which make use of that function, was never updated to accommodate this change.
I think that this is the only other place where this function is used.

Fix baseline ordering error in RFI mask

---

draco/analysis/beamform.py
draco/synthesis/mockcatalog.py

`verbose` keywords have been deprecated since `healpy 1.15.0`

fix(beamform, mockcatalog): remove deprecated `healpy` verbose keyword

---

draco/analysis/powerspec.py

Calculates the cross-power spectrum between all polarisation pairs. I think it's worth computing this every time as a consistency check. The logic was moved out of `get_3D_ps` since it involves only a simple multiplication.

feat(powerspec): calculate power spectrum for all polarisation pairs

---

draco/analysis/beamform.py
draco/analysis/dayenu.py
draco/analysis/flagging.py
draco/core/containers.py

* Replace CombineMasks with a GeneralCombineMasks task that can construct
arbitrary combinations of masks.
* Create ApplyTaper task, which applies a taper to a RingMap.
* Introduce GeneralCombineTapers task for arbitrary taper combination.
* Add MaskFromTaper task to generate binary masks from taper thresholds.
* Define new container RingMapTaper and HorizonLimit container.
* Do not create datasets if they already exist in DayenuDelayFilterHybridVis.
* Fix bug in FitBeamForm.

feat(flagging): refactor mask logic, add taper support

---

draco/analysis/dayenu.py
draco/analysis/flagging.py
draco/analysis/hyforesbandpass.py
draco/analysis/powerspec.py
draco/analysis/ringmapmaker.py
draco/analysis/sidereal.py
draco/analysis/transform.py
draco/core/containers.py
draco/synthesis/noise.py

Applying the Dayenu filter introduces off-diagonal terms in the
frequency-frequency noise covariance matrix.  Update the following
tasks to calculate this covariance matrix:
- DayenuDelayFilterHybridVis
- DayenuDelayFilterHybridVis
- DelayFilterHyFoReSBandpassHybridVisClean
Also update the following tasks to propagate this covariance matrix
through the pipeline:
- SiderealRebinner
- SiderealStacker
- RADependentWeights
- SelectPol
The covariance matrix is saved as a new dataset named either
freq_cov or complex_freq_cov in the HybridVisStream or RingMap,
similar to how the filter itself is saved.
Creates two new tasks:
- ConstructWienerDelayTransform
- ApplyWienerDelayTransform
that implement a Wiener-filtered delay transform that:
- handles frequency masks with non-uniform coverage
- …

feat: track freq-freq covariance matrix

---

draco/core/io.py

Useful to do something like the following:
```yaml
- type: draco.core.io.LoadFilesFromPathAndTag
out: file
params:
paths: ["revision/path/1/{tag}/sstream_{tag}.h5", "revision/path/2/{tag}/sstream_{tag}.h5"]
tags: ["1878", "1932"]
```
which would load files for each combination of path and tag.
I wasn't able to reproduce this behaviour with any other existing tasks, so I figured that adding this new task is ok.

Task to load files from combinations of paths and tags

---

draco/analysis/powerspec.py

There are two tasks to properly scale the noise to account for the spatial variation of T_sky. 
1. GenerateNoiseScaleFactor  - This task generates a noise scale factor
2. ScaleDelayTransform - This task applies the scale factor to the noise delay spectrum.

generate scale factor and apply that to the noise delay spectrum

---

draco/analysis/sidereal.py
draco/analysis/transform.py
draco/util/_fast_tools.pyx
draco/util/dpss.py
draco/util/gaussian_process.py
draco/util/kernels.py
draco/util/regrid.py
setup.py

Implements a simple GP interpolator for resampling, and a task to use this as a sidereal regridder.
This PR makes a handful of minor changes to the structure of the `Regridder` code, but I think I've managed to avoid any impacts on end users. One point of note is that I've updated the various `SiderealRegridder` tasks to take a `SiderealStream` as input.
- Updated to support sample values as inputs, rather than just a range
- Added a periodic kernel
- Added helpers for getting the main band of a band-diagonal kernel
Implements GP resampling/interpolation. The main functions are:
- Interpolates signal + noise and propagates weights
Figures out which samples we can interpolate onto, based solely on the initial mask and the width of the kernel.
- Adds a `_banded_matmul` function, which is …

Implement a GP regridder

---

draco/analysis/interpolate.py
draco/util/dpss.py

Lets us use the dpss inpainting task as a low-pass filter. I guess this is similar to what's provided by dayenu, but I figured there's no harm in supporting it here

Support dpss filtering without inpainting

---

draco/analysis/dayenu.py
draco/analysis/delay.py
draco/analysis/flagging.py
draco/analysis/hyforesbandpass.py
draco/analysis/powerspec.py
draco/analysis/ringmapmaker.py
draco/analysis/sensitivity.py
draco/analysis/svdfilter.py
draco/synthesis/stream.py
draco/util/filters.py
draco/util/tools.py

The Stokes I mask code is a bit messy and the second stage is questionable (although at the moment, there are a handful of narrow RFI bands that don't get caught anywhere else). This PR splits the task into separate tasks, by creating a base `RFIVisMask` task and two derived tasks.
It also creates a new `util.filters` module, and moves some basic filters from elsewhere:
- weighted convolution highpass/lowpass filter
- median filter (basically just calls `caput.moving_weighted_median`, but handles complex data)
- null delay filter (changed to `null_filter`)
It may be helpful to look at the commits individually.
There will be a second PR which is currently based against this branch, but I wanted to split them up.
Also, some `ruff` updates.

Split Stokes I mask into separate tasks
