draco/core/containers.py

- Made container types inheritable.
- Added a new base class for constructing table based containers.
- Create new containers for holding tables of spectroscopic objects.

Container improvements: inheritance and table types

---

draco/analysis/transform.py
draco/core/containers.py
draco/synthesis/noise.py

Mmodes need a stack axis to be compatible with stacked data, and a couple of bug fixes

Mmodes fix

---

draco/analysis/transform.py

I would like to have the capability to slice the mmodes at the telescope mmax if requested. 
(when we have more time samples in the visibilities than 2*mmax + 1)

Make MModeTransform slice mmodes at tel_mmax if requested

---

doc/conf.py
draco/__init__.py
draco/analysis/delay.py
draco/analysis/fgfilter.py
draco/analysis/flagging.py
draco/analysis/mapmaker.py
draco/analysis/powerspectrum.py
draco/analysis/sidereal.py
draco/analysis/svdfilter.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/core/misc.py
draco/core/task.py
draco/synthesis/gain.py
draco/synthesis/noise.py
draco/synthesis/stream.py
draco/util/regrid.py
draco/util/tools.py
setup.py

This should be everything required to support Python 3.

Python 3 support

---

draco/analysis/flagging.py

Currently the `weight` dataset output by `SiderealRegridder` will have a minimum value given by the assumed inverse variance of the signal (specifically the `snr_cov` config property, which defaults to 1e-8).
This is not ideal as we often use `weight == 0.0` to indicate missing or flagged data.  Since `snr_cov` is set to a very small number, this will not cause a problem for tasks following the `SiderealRegridder` which use inverse variance weighting.  However, tasks that use uniform or natural weighting will end up including bad data, and any estimate of the noise that is obtained by propagating the weights will likely be ruined (e.g., the `rms` dataset in the ringmaps with natural weighting).
I suggest we correct the `SidrealRegridder` so that the output weights are zero if the input …

feat(flagging): add task that sets weights below threshold equal to zero

---

draco/analysis/sidereal.py

- Add two config properties to `SiderealGrouper` that allow it to be used
to process a window around source transit.  This is necessary for analysis of `chimecal` data.
-- `min_day_length` was a previously hardcoded parameter (defaults to that same value).
-- `offset` is used to prevent wrapping for sources near RA=0 or 360 deg. (defaults to 0.0,
which yields previous behaviour).
- Fix log message describing LSD that is being concatenated.
- Use `tools.invert_no_zero` for normalizing visibilities to prevent divide by zero
warnings in log.

feat(sidereal): update `SiderealGrouper` to handle source transits

---

draco/analysis/beamform.py
draco/core/containers.py
draco/util/_fast_tools.pyx
draco/util/tools.py

This version of beamform has been tested on Python 3.

Beamform dev py3

---

draco/synthesis/noise.py

- if an optional manager object is passed to this task, it calculates the redundant baselines from the telescope object and simulates gaussian noise accordingly.

feat(GaussianNoise): Consider redundancy of baselines

---

draco/analysis/qstack.py
draco/analysis/sourcestack.py
draco/core/containers.py

This is the much simpler version of the quasar stacker that uses the product of the beamformer ( #33 ).

Qstack dev

---

draco/analysis/transform.py

Fixes the problem of missing highest modes when using `transform._pack_marray` to pack an FFT into the correct format for the m-modes.
The old function would always discard the two highest positive m-modes and their respective negative pairs. When the length of the FFT, `N`, is even and `mmax=None` or `mmax>=N//2` the function would discard the Nyquist term and the second highest positive m-mode with its respective negative pair. The new function fixes these problems. 
Below are some examples with `N` even
```
input:
mmodes=[1.+1.j 2.+2.j 3.+3.j 4.+4.j 5.+5.j 6.+6.j 7.+7.j 8.+8.j], mmax=None
output with OLD _pack_marray:
[[1.+1.j 0.+0.j]
[2.+2.j 8.-8.j]
[3.+3.j 7.-7.j]
[0.+0.j 0.+0.j]
[0.+0.j 0.+0.j]]
output with NEW _pack_marray:
[[1.+1.j 0.+0.j]
[2.+2.j 8.-8.j]
[3.+3.j 7.-7.j]
[4.+4.j …
```

fix(transform._pack_marray): Missing highest modes when packing FFT in m-mode format

---

draco/analysis/ringmapmaker.py

- Fix bug preventing excluding autos
- Use the weight type parameter
- Normalise the beamformed output by the sum of the weights

A few fixes to NS beamforming

---

draco/analysis/beamform.py
draco/analysis/flagging.py
draco/analysis/mapmaker.py
draco/analysis/sensitivity.py
draco/analysis/sourcestack.py
draco/analysis/transform.py
draco/core/containers.py
draco/synthesis/gain.py
draco/util/tools.py
setup.py

Pipeline task to create datasets for weights, and autocorrelation derived noise estimates.

[WIP] Radiometer metric

---

draco/synthesis/noise.py

feat(gaussiannoise): add a gaussian noise dataset generator

---

draco/analysis/flagging.py

Because of the large variation in weights across stacked baselines it's more appropriate to do the thresholding relative to the mean level of each baseline. Without this it's impossible to set appropriate thresholding for the delay spectrum estimator.
@ssiegelx I think you only use this task with the absolute threshold, right? Is this change going to break anything you do?

Apply relative threshold per baseline

---

draco/analysis/flagging.py
draco/core/containers.py
draco/core/misc.py

This adds the common mode gain containers (sidereal and time) and modifies AppyGains to use them.

common mode gain dev

---

draco/synthesis/noise.py

- randomgen 1.18 renamed RandomGenerator to Generator.
This commit renames Generator back to RandomGenerator on import
for synthesis.noise, in the same way as was done in analysis.delay.
- Fixes bug in how autocorrelations are being identified in GaussianNoiseDataset
- Fixes inconsistent variable name in mpi_random_seed
(both 'gen' and 'randomgen' are used to refer to the same variable)

fix(noise): RandomGenerator rename and other GaussianNoiseDataset bugs

---

draco/analysis/beamform.py
draco/analysis/sourcestack.py
draco/core/io.py
draco/synthesis/noise.py
draco/util/random.py
requirements.txt

Here's a bundle of some stacking related changes:
- There's a decent speedup in the beamform code
- Most of the work is to be able to load the SDSS catalogs from the released FITS files and generating random catalogs by subsampling the official SDSS random catalogs.
- Some refactoring of the code which handles random number generation and seeding. I've deprecated the `mpi_random_seed` context manager in favour of a pipeline baseclass which does a better job of the same thing.

SDSS stacking related changes

---

.github/workflows/main.yml
doc/pipeline_params.yaml
draco/core/io.py
draco/util/exception.py
examples/test.yaml
test/test_io.py
test/test_write_metadata.py

Depends on https://github.com/radiocosmology/caput/pull/147

feat(io): raise ConfigError if file not found

---

draco/core/containers.py
draco/core/task.py

Added a baseclass for containers that have a Healpix pixelised axis.

feat(containers): added a HealpixContainer baseclass

---

draco/analysis/sourcestack.py
draco/core/containers.py

Creates FrequencyStackByPol container, which is a
FrequencyStack container with a polarisation axis.
Updates SourceStack to use the FrequencyStackByPol
container and stack each polarisation separately if
the input  FormedBeam container has more than
one polarisation.

feat(sourcestack): separately stack each pol

---

draco/core/containers.py

Used as an input to the driftscan beam transfer matrix calculation.

feat(core.containers): HEALPixBeam container.

---

draco/analysis/beamform.py
draco/analysis/delay.py
draco/analysis/flagging.py
draco/analysis/mapmaker.py
draco/analysis/ringmapmaker.py
draco/analysis/sidereal.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/core/misc.py
draco/util/random.py
draco/util/rfi.py

This is built on top of #65 and so should be repointed when that one is merged.

Stacking and delay filter changes

---

draco/core/task.py

Discovered when testing for: https://github.com/radiocosmology/caput/pull/162
`isnan()`, `any()`, and `sum()` all invoke ufuncs, and sometimes if a nan or inf are present, some MPIArray ranks will fall out of sync. The current fix is to try to limit this from happening, by avoiding the `any()` conditional, and working with local arrays directly, since the full MPIArray is not needed to run these checks. We only need to return a Boolean depending on if nans or infs are present.

fix(isnan): check for NaN/Inf in local arrays, to avoid crashes due to de-syncing 

---

draco/synthesis/mockcatalog.py

- feat(mockcatalog): add a tracer attribute to pdfs and mockcatalogs
- fix(AddEBOSSZErrorsToCatalog): bug when using tracer from catalog

Fix bug using tracer and allow setting of it 

---

draco/analysis/beamform.py
draco/analysis/ringmapmaker.py
draco/analysis/transform.py
draco/core/task.py

- fix(ringmapmaker): make complex to real cast explicit
- feat(MixData): a task for generating arbitrary mixes of data and weights
- fix(TransformJanskyToKelvin): incompatibility with CHIMEExternalBeam

Mix data and fix flux cal bug

---

draco/analysis/beamform.py
draco/analysis/dayenu.py
draco/analysis/delay.py
draco/analysis/flagging.py
draco/analysis/mapmaker.py
draco/analysis/ringmapmaker.py
draco/analysis/sensitivity.py
draco/analysis/sidereal.py
draco/analysis/transform.py
draco/core/containers.py
draco/synthesis/gain.py
draco/synthesis/noise.py
draco/synthesis/stream.py
draco/util/random.py
draco/util/rfi.py

Needed along with c83f70577f631b70e6

fix(beamform): return before requiring self.epoch

---

draco/analysis/beamform.py
draco/synthesis/mockcatalog.py

- feat(HealpixBeamForm): add an option to smooth the map before extraction
- feat(mockcatalog): add a new redshift dependent QSO z-error model

New QSO z-error model

---

draco/core/containers.py
draco/core/misc.py
test/test_selections.py

Also adds an optional `update_id` dataset to the `GainData` container.

fix(containers): add input axis to GainData weight dataset

---

draco/analysis/delay.py
draco/analysis/flagging.py
draco/analysis/ringmapmaker.py
draco/analysis/sensitivity.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/misc.py

This add the optional ability to copy over datasets from an existing container when creating a new one.
This also updates the docstring to document all the existing arguments to the constructor.

feat(ContainerBase): copy over datasets when creating a container

---

draco/analysis/flagging.py

This also removes the deprecated destriping functionality.

feat(RFIMask): calculate RFIMask container rather than applying in place.

---

draco/analysis/flagging.py
draco/core/io.py

- feat(io): provided feedback on progress when reading files
- fix(flagging): resolve lingering MPIArray issues

Improve the debug messages when loading files

---

draco/util/regrid.py

This removes the bias introduced by the signal covariance in the
returned noise estimate. Practically this means that regions
corresponding to missing data will end up with an inverse noise estimate
of zero, and not a small but finite value.

fix(regrid): remove bias in inverse noise estimate

---

draco/core/io.py

- fix(io): issue loading zarr files with selections
- fix(io): correctly check for the existence of zarr containers

Fix issues doing IO with zarr

---

draco/core/misc.py

Add @tristpinsm 's `MakeCopy` task to copy a container

feat(misc): add task to deep copy a container

---

draco/analysis/flagging.py
draco/core/io.py

- feat(BlendStack): add an option to subtract rather than average the data
- feat(ThresholdVisWeightBaseline): reintroduce the old ThresholdVisWeight

Flagging Changes

---

draco/core/misc.py

This task just confirms that all mpi processes can communicate with each other. Not sure if there is a better place to put the task

feat(misc): add task to test mpi communication

---

draco/analysis/beam.py
draco/analysis/beamform.py
draco/analysis/dayenu.py
draco/analysis/delay.py
draco/analysis/fgfilter.py
draco/analysis/flagging.py
draco/analysis/mapmaker.py
draco/analysis/ringmapmaker.py
draco/analysis/sensitivity.py
draco/analysis/sidereal.py
draco/analysis/sourcestack.py
draco/analysis/svdfilter.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/core/misc.py
draco/core/task.py
draco/synthesis/gain.py
draco/synthesis/noise.py
draco/synthesis/stream.py
draco/util/random.py
draco/util/regrid.py
draco/util/rfi.py
draco/util/tools.py
test/test_containers.py
test/test_io.py
test/test_tools.py

This includes removing the redundant BaselineAlt copy and renaming the frequency-dependent version for consistency.

refactor(flagging): clean up various versions of ThresholdVisWeight.

---

draco/analysis/flagging.py

~~The previous implementation looped over each frequency individually.
This can be accomplished by setting the window size to 1 in the median
filter, meaning that we only need one median filter call. The filter can
also be done in-place, removing an extra memory allocation (this
probably won't change much since it's a fairly small array).~~
Looping is still done and we instead use `caput.moving_weighted_median` for speed

perf(SmoothVisWeight): Use caput `moving_weighted_median`

---

draco/analysis/flagging.py

Most baseline dependent masking has been done in place. To follow the convention of separating masking tasks into those that create masks and those that apply masks, this task lets us directly apply `BaselineMask` and `SiderealBaselineMask` containers to timestream or sidereal stream without having to collapse it to just a time-freq mask.
This is needed to properly replicate the behaviour of the previous `ThresholdVisWeightBaselineAlt` task, and more generally to apply any baseline-dependent mask. Optionally, `ThresholdVisWeightBaseline` could be given an `in_place` flag

feat(flagging): introduce a task to apply a baseline-dependent mask.

---

draco/core/containers.py
draco/core/io.py

- feat(containers): routine for combining all dataset specs on a class
- fix(Truncate): ensure truncation is applied to all datasets in a container

Ensure truncation is applied to all datasets

---

draco/analysis/sidereal.py

This is a dumb one - somehow I missed that this already exists (and has always existed)

fix(sidereal): remove unnecessary copy

---

.github/workflows/main.yml
draco/analysis/beamform.py
draco/analysis/delay.py
draco/analysis/transform.py
draco/core/containers.py
draco/core/io.py
draco/util/regrid.py
draco/util/testing.py
pyproject.toml
setup.py

Python 3.8 reaches end-of-life in October 2024

Increase minimum supported python to 3.9

---

draco/analysis/flagging.py

a small bug in applying a time-freq mask to data

bug_apply_time_freq_mask

---

draco/analysis/dayenu.py

This PR does two things:
1. Adds an option to generate but not apply a dayenu high-pass filter. At the moment, this is only implemented for hybrid vis datasets, but should probably be consistent everywhere
2. Extend the task which applies an existing filter so that it can be used with different loop options. Previously, only a single filter could be applied to multiple dataset, since the filter was provided in the `setup` method which can only run once. This behaviour is preserved in the new task. The alternate behaviour is to provide both the filter and the dataset to filter in the `process` method, which lets us split up the process of generating and applying a filter to each dataset

Skip applying dayenu filter and add options when applying existing filter

---

draco/core/containers.py

Still need to test to make sure truncation effects are not significant

Add DelayTransform compression and increase SiderealStream chunk size

---

draco/analysis/dayenu.py

Also ensure there are no masked frequencies in the data that were unmasked during filter generation.

fix(dayenu): do not apply atten_threshold to fully masked samples

---

draco/analysis/flagging.py

Support `Ringmap` and `HybridVisStream` data. Still needs testing.

Update BlendStack to support different container types

---

draco/analysis/beam.py
draco/analysis/transform.py
draco/core/containers.py
pyproject.toml

This is untested so far, but I think it should work.

Task to mix exactly two datasets in a single iteration

---

draco/analysis/hyforesbandpass.py
draco/core/containers.py

The hyforesbandpass module estimates bandpass gains from daily hybrid beamformed visibilities, save the estimated gains, and the correct and delay filter the daily hybrid beamformed visibilities. Additional containers were added to the container module.

Adding hyforesbandpass module to implement hyfores

---

draco/analysis/flagging.py

Updated ApplyTimeFreqMask to allow the input RFI mask and tstream data to have different lengths along the RA/time axes.

Updated ApplyTimeFreqMask to support flexible inpuut axis lengths.

---

draco/core/containers.py

Add compression option to LocalizedRFIMask and SiderealLocalizedRFIMask containers.

feat(container): add compression option to RFI mask containers

---

draco/analysis/transform.py
draco/util/tools.py

* Extend `SelectPol` to extract arbitrary Stokes parameters (I, Q, U, V)
* Add `PolWeightedAverage` task to compute optimal pseudo-Stokes I from XX and YY.
* Modify `MixData` to support optional mixing of tags via `tag_coeff`.
* Add `broadcast_weights` utility for matching weight and data shapes.

feat(transform): improve polarisation handling

---

draco/analysis/transform.py

Create flag array with correct data type.  Index it properly when constructing the output weights dataset.

fix(transform): fix bug in SelectPol

---

draco/analysis/flagging.py
draco/core/containers.py

This task adjusts the time axis of an RFI mask to match the time axis of a target timestream data.

feat(flagging): add AlignMaskTime task to adjust the time axis of an RFI mask using nearest-interpolation

---

draco/analysis/transform.py

Include both fftW and numpy fft option while generating m-arrays in MModeTransform

include fftW parametes

---

draco/analysis/ringmapmaker.py

Add exclude_cyl config property to DeconvolveHybridMBase that allows one to exclude an arbitrary number of east-west baselines.

feat(ringmapmaker): flexible cylinder exclusion in DeconvolveHybridMBase

---

draco/analysis/beamform.py

Update RingMapBeamForm and RingMapStack2D to handle partial maps of the sky.  Sources that fall outside of the RA and Dec range covered by the map will be excluded from the beamformed output or 2D stack.

feat(beamform): more flexible ringmap-based source stacking

---

draco/analysis/flagging.py

In a few cases, pipeline jobs have failed due to NaN values in the sensitivity metric. I've traced this back to negative autocorrelation values introducing NaNs when taking a square root. I don't think there's any possible way for this to be physical, so we should mask these values early-on in the daily pipeline.
This task hasn't been tested at scale yet, but I think it should work fine.

Mask samples with negative autos

---

draco/analysis/sourcestack.py

Add a uniform weighting option in stacking pipeline.

uniform weighting

---

draco/analysis/flagging.py

For one reason or another, the masked median used by `np.ma.median` is significantly slower than the standard median, which is itself slower than our cython implementation.

Use faster median in ThresholdVisWeightBaseline
